version: '3.4'
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Your_Password123'
    ports:
      - '1433:1433'
    restart: always    
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - './mongodb_data_container:/data/db'
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672